[".zinit"]
    type = "archive"
    url = "https://github.com/zdharma-continuum/zinit/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

{{ if eq .chezmoi.os "windows" }}
["AppData/Local/nvim-data/site/autoload/plug.vim"]
{{ end }}
{{ if ne .chezmoi.os "windows" }}
[".local/share/nvim/site/autoload/plug.vim"]
{{ end }}
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".volta"]
    type = "archive"
    url = 'https://github.com/volta-cli/volta/releases/latest/download/volta-{{- output "curl" "https://volta.sh/latest-version" | trim -}}-{{ .volta.variant }}{{ .volta.ext }}'
    refreshPeriod = "168h"