[".zinit"]
    type = "archive"
    url = "https://github.com/zdharma-continuum/zinit/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"

[".config/bat/themes/Catppuccin Macchiato.tmTheme"]
    type = "file"
    url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Macchiato.tmTheme"
    refreshPeriod = "168h"

[".config/fsh/catppuccin-macchiato.ini"]
    type = "file"
    url = "https://github.com/catppuccin/zsh-fsh/raw/main/themes/catppuccin-macchiato.ini"
    refreshPeriod = "168h"

[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

{{ if eq .chezmoi.os "linux" }}
[".local/share/fonts/neogdm.tff"]
    type = "file"
    url = "https://github.com/neodgm/neodgm/releases/latest/download/neodgm.ttf"
    refreshPeriod = "168h"

[".local/share/fonts/cascadia-code-nf"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.zip"
    exclude = ["Windows Compatible"]
    refreshPeriod = "168h"
{{ end }}
